server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/wenhailin/Work/demo/config-repo
        default-label: main
#          force-pull: true
#          uri: https://github.com/myorg/{application}
#          skip-ssl-validation: true
#          timeout: 30
#          repos:
#            simple: https://github.com/simple/config-repo
#            special:
#              pattern:
#                - special*/*.dev*
#              uri: https://github.com/special/config-repo
#          search-paths:
#            - foo
#            - bar
#          username: root
#          password: root